

#########################
## program compilation

question1: question1.c
	gcc -Wall -o question1 question1.c -lm


# add your own rules when you create new programs



#########################
## utilities

clean:
	rm -f question1 question2 tiny.txt small.txt medium.txt large.txt many.txt 

